name: devbox

services:
  devbox:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}
    volumes:
      - workspace:/workspace
      - ${DEVBOX_DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock
      - ${DEVBOX_SSH_AUTH_SOCK:-/run/host-services/ssh-auth.sock}:/ssh-agent
    environment:
      SSH_AUTH_SOCK: /ssh-agent
      GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=accept-new
      DOCKER_HOST: unix:///var/run/docker.sock
    working_dir: /workspace
    tty: true
    stdin_open: true
volumes:
  workspace:
